//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fbg.Bll.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Misc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Misc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fbg.Bll.Properties.Misc", typeof(Misc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}. You are under attack in Realm of Empires!
        ///&lt;BR&gt;&lt;BR&gt;First attack landing at {2} local time. &lt;a href=&apos;http://apps.facebook.com/realmofempires/?ccid=2&amp;ccm=9&apos;&gt;Defend yourself!&lt;/a&gt;
        ///&lt;BR&gt;&lt;BR&gt;Note, you will not receive further alerts from this realm until you login to the realm, even if a new attack, landing earlier than this one, is launched. .
        /// </summary>
        internal static string email_AttackIn_Body {
            get {
                return ResourceManager.GetString("email_AttackIn_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are under attack in Realm of Empires, {0}.
        /// </summary>
        internal static string email_AttackIn_Subject {
            get {
                return ResourceManager.GetString("email_AttackIn_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}, your Beginner Protection runs out in just {2} hours! 
        ///
        ///&lt;BR&gt;&lt;BR&gt;&lt;B&gt;What does this mean?&lt;/b&gt; This means you will be vulnerable to attacks. Other players will be able to attack you to loot your silver, destroy your buildings or even take your hard-earned city from you!.
        ///
        ///
        ///&lt;BR&gt;&lt;BR&gt;&lt;a href=&apos;http://apps.facebook.com/realmofempires/?ccid=2&amp;ccm=10&apos;&gt;&lt;B&gt;Login now!&lt;/B&gt;&lt;/a&gt;
        ///
        ///
        ///&lt;BR&gt;&lt;BR&gt;&lt;B&gt; Here are some tips how you can protect yourself:&lt;/B&gt;
        ///&lt;BR&gt; &gt; Join a good clan
        ///&lt;BR&gt; &gt; Recruit troops. Infantry is a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_BPEnding_Body {
            get {
                return ResourceManager.GetString("email_BPEnding_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready? Wars may begin in {0} hours.
        /// </summary>
        internal static string email_BPEnding_Subject {
            get {
                return ResourceManager.GetString("email_BPEnding_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey {3} {4}!
        ///
        ///&lt;BR&gt;&lt;BR&gt; I just invited you to my clan {0}&lt;/B&gt; in &lt;a href=&apos;http://apps.facebook.com/realmofempires/?ccid=2&amp;ccm=5&amp;goto=clanoverview.aspx&apos;&gt;Realm Of Empires&lt;/a&gt;!
        ///
        ///&lt;BR&gt;&lt;BR&gt;Hope to see you there! Cheers!
        ///&lt;BR&gt;{1} {2}
        ///
        ///&lt;BR&gt;&lt;BR&gt;&lt;a href=&apos;http://apps.facebook.com/realmofempires/?ccid=2&amp;ccm=5&amp;goto=clanoverview.aspx&apos;&gt;Accept&lt;/a&gt; or &lt;a href=&apos;http://apps.facebook.com/realmofempires/?ccid=2&amp;ccm=5&amp;goto=clanoverview.aspx&apos;&gt;Reject&lt;/a&gt; the invitation.
        ///
        ///&lt;BR&gt;&lt;BR&gt; &lt;i&gt;Clan is a loose federation of players wor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_ClanInvite_Body {
            get {
                return ResourceManager.GetString("email_ClanInvite_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} invited you to a clan.
        /// </summary>
        internal static string email_ClanInvite_Subject {
            get {
                return ResourceManager.GetString("email_ClanInvite_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0} {1},
        ///                &lt;br /&gt;
        ///                &lt;br /&gt;
        ///                This is a notification that you received an email from {3} on {2}
        ///                &lt;br /&gt;
        ///                &lt;br /&gt;
        ///&lt;HR&gt;
        ///&lt;B&gt;Subject:&lt;/B&gt;{4}
        ///&lt;BR&gt;&lt;B&gt;Message:&lt;/B&gt;{5} ...
        ///&lt;HR&gt;
        ///You currently have {6} unread messages on {2}. &lt;a href=&quot;http://apps.facebook.com/realmofempires/?ccid=2&amp;ccm=12&quot;&gt;&lt;B&gt;Login&lt;/B&gt;&lt;/a&gt; to check your messages
        ///                &lt;br /&gt;
        ///                &lt;br /&gt;
        ///Note, you will not receive further alerts from this real [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_EmailNotify_Body {
            get {
                return ResourceManager.GetString("email_EmailNotify_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email from {0} : &apos;{1}&apos;.
        /// </summary>
        internal static string email_EmailNotify_Subject {
            get {
                return ResourceManager.GetString("email_EmailNotify_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;
        ///            &lt;div style=&quot;color: #FFFFFF;
        ///            font-size: 11px;
        ///            background-color: #000000;
        ///            clear: both;&quot;&gt;
        ///                This is an automated player alert from the Facebook game &lt;a href=&quot;http://apps.facebook.com/realmofempires/?ccid=2&amp;ccm={0}&amp;ccd=roe&quot; style=&quot;color: #FFD886;
        ///            text-decoration: none;&quot;&gt;Realm Of Empires&lt;/a&gt;; please do not reply
        ///                &lt;br /&gt;
        ///                You are receiving this email beacuse you authorized Realm of Empires in fac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_footer {
            get {
                return ResourceManager.GetString("email_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/REC-html40/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;center&gt;
        ///&lt;table width=620&gt;&lt;TR&gt;&lt;TD&gt;
        ///        &lt;div style=&quot;width: 620px; border: solid 2px black;&quot;&gt;
        ///            &lt;img src=&quot;https://static.realmofempires.com/images/ROE_Email_Header_620.jpg&quot; border=&quot;1&quot; alt=&quot;Realm Of Empires Logo&quot; /&gt;
        ///            &lt;div style=&quot;background-color: #DDDDAA;padding:5px 5px 5px 5px;&quot;&gt;
        ///                &lt;br /&gt;.
        /// </summary>
        internal static string email_header {
            get {
                return ResourceManager.GetString("email_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///&lt;style&gt;
        ///@import url(http://fonts.googleapis.com/css?family=Eagle+Lake);
        ///@media only screen and (max-device-width: 480px) {
        ///	.mainBodyDiv{
        ///		width: 480px; !important;
        ///	}
        ///
        ///}
        ///
        ///	.mainBodyTable {
        ///
        ///		background-size: 480px auto !important;
        ///	}
        ///
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;div class=&quot;mainBodyDiv&quot; style=&quot;width: 480px; height:auto; font-family: Calibri,sans-serif;&quot;&gt;
        ///	&lt;table class=&quot;mainBodyTable&quot; background=&quot;https://static.realmofempires.com/images/email/midtexture.jpg&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cell [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_header2 {
            get {
                return ResourceManager.GetString("email_header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0} {1},
        ///                &lt;br /&gt;
        ///                &lt;br /&gt;
        ///                This is a notification that you have been inactive for at least 7 days on {2}.                
        ///                &lt;br /&gt;
        ///                &lt;br /&gt;
        ///                Players that are inactive for 14 days are removed from the realm - they lose all their villages which go &quot;abandoned&quot; 
        ///                and can fall into enemies&apos; hands.
        ///                &lt;BR /&gt;&lt;BR /&gt;To prevent going abandoned, please make sure you &lt;a href=&quot;http://apps.face [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_Inactive_Body {
            get {
                return ResourceManager.GetString("email_Inactive_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your kingdom is about to be abandoned.
        /// </summary>
        internal static string email_Inactive_Subject {
            get {
                return ResourceManager.GetString("email_Inactive_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!,&lt;BR/&gt;&lt;BR/&gt;You have requested to reset the password of your Realm of Empires Tactica account.
        ///
        ///&lt;BR&gt;&lt;BR&gt;Please click on the following link to reset your password: &lt;a href=&apos;{0}&apos;&gt;{0}&lt;/a &gt;. 
        ///
        ///&lt;BR&gt;&lt;BR&gt;If you did not request this password reset, please ignore and delete this email, your account is safe. 
        ///
        ///&lt;BR/&gt;&lt;BR/&gt;Sincerely,&lt;BR/&gt;&lt;strong&gt;The Realm of Empires Team.&lt;/strong&gt;&lt;BR/&gt; &lt;BR/&gt;.
        /// </summary>
        internal static string email_resetpassword_body {
            get {
                return ResourceManager.GetString("email_resetpassword_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;
        ///            &lt;div style=&quot;color: #FFFFFF;
        ///            font-size: 11px;
        ///            background-color: #000000;
        ///            clear: both;&quot;&gt;
        ///                This is an automated player alert from the Facebook game &lt;a href=&quot;http://apps.facebook.com/realmofempires/?ccid=2&amp;ccm={0}&amp;ccd=roe&quot; style=&quot;color: #FFD886;
        ///            text-decoration: none;&quot;&gt;Realm Of Empires&lt;/a&gt;; please do not reply
        ///                &lt;/br&gt;
        ///                To ensure you do not miss such an alert, please add the sender of this messa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_resetpassword_footer {
            get {
                return ResourceManager.GetString("email_resetpassword_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string email_resetpassword_subject {
            get {
                return ResourceManager.GetString("email_resetpassword_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!,&lt;BR/&gt;&lt;BR/&gt;You have requested to reset the password of your Realm of Empires Tactica account.
        ///
        ///&lt;BR&gt;&lt;BR&gt;Your new, randomly generated password is &lt;div style=&apos;font-family: &quot;Courier New&quot;, Courier, monospace;  font-size: 16pt;&apos;&gt;&lt;B&gt;{0}&lt;/B&gt;&lt;/div&gt;
        ///
        ///&lt;BR&gt;&lt;BR&gt;Please go to your settings in-game and change this password as soon as possible. If you did not request this reset, please contact support at support@RealmOfEmpires.com
        ///
        ///&lt;BR/&gt;&lt;BR/&gt;Sincerely,&lt;BR/&gt;&lt;strong&gt;The Realm of Empires Team.&lt;/strong&gt;&lt;BR/&gt; &lt;BR/&gt;.
        /// </summary>
        internal static string email_resetpasswordDone_body {
            get {
                return ResourceManager.GetString("email_resetpasswordDone_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.
        /// </summary>
        internal static string email_resetpasswordDone_subject {
            get {
                return ResourceManager.GetString("email_resetpasswordDone_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Realm of Empires!
        ///
        ///&lt;BR&gt;&lt;BR&gt;Thank you for registering
        ///
        ///&lt;BR&gt;&lt;BR&gt;Please &lt;a href=&apos;{0}/Verify.aspx?uid={1}&apos;&gt;click here to verify your email&lt;/a &gt;.  This is necessary to secure your Tactica Account.  
        ///
        ///&lt;BR&gt;&lt;BR&gt;Let the battles begin!
        ///
        ///&lt;BR/&gt;&lt;BR/&gt;Sincerely,&lt;BR/&gt;&lt;strong&gt;The Realm of Empires Team.&lt;/strong&gt;
        ///
        ///&lt;BR&gt;&lt;BR&gt;P.S. If you did not create a Tactica account, please ignore and delete this email..
        /// </summary>
        internal static string email_verifyemail_onregistration_body {
            get {
                return ResourceManager.GetString("email_verifyemail_onregistration_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Realm of Empires. Email verification required for security..
        /// </summary>
        internal static string email_verifyemail_onregistration_subject {
            get {
                return ResourceManager.GetString("email_verifyemail_onregistration_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE READ THE FOLLOWING CAREFULLY AND ONLY COMPLETE THIS IF IT IS CORRECT.&lt;BR/&gt;&lt;BR/&gt;Someone (maybe you) has requested to recover their account associated with this email. 
        ///
        ///&lt;BR&gt;&lt;BR&gt;If this was not you, then just delete and ignore this email  - no further action from your end is necessary. Your account is safe.
        ///
        ///&lt;BR&gt;&lt;BR&gt;For your reference, the account that is associated with this email address has the following player(s): {0}. 
        ///
        ///&lt;BR&gt;&lt;BR&gt;If it is you who requested to recover this account, and want to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_verifyrecoveraccountbody {
            get {
                return ResourceManager.GetString("email_verifyrecoveraccountbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE READ THE FOLLOWING CAREFULLY.&lt;BR/&gt;&lt;BR/&gt;Someone (maybe you) has requested to recover their account associated with this email.  However this account is a FACEBOOK account.  Please go back to Realm of Empires and tap &apos;I DID THAT, NOW LOG ME IN&apos; or just login with &apos;VIA FACEBOOK&apos;.
        ///
        ///&lt;BR&gt;&lt;BR&gt;If this was not you, then just delete and ignore this email  - no further action from your end is necessary. Your account is safe.
        ///
        ///&lt;BR&gt;&lt;BR&gt;For your reference, the account that is associated with this email address [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_verifyrecoveraccountbodyforfb {
            get {
                return ResourceManager.GetString("email_verifyrecoveraccountbodyforfb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm of Empires account email verification for the following player(s): {0}.
        /// </summary>
        internal static string email_verifyrecoveraccountsubject {
            get {
                return ResourceManager.GetString("email_verifyrecoveraccountsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;
        ///&lt;/td&gt;				
        ///			&lt;/tr&gt;
        ///			
        ///			
        ///			
        ///			
        ///			&lt;!-- Bottom Spacer --&gt;
        ///			&lt;tr&gt;
        ///				&lt;td style=&quot;padding: 10px;&quot;&gt;&lt;/td&gt;
        ///			&lt;/tr&gt;	
        ///			
        ///
        ///			&lt;!-- Bottom Image --&gt;
        ///			&lt;tr&gt;&lt;td style=&quot;padding: 0px;&quot;&gt;&lt;img class=&quot;mainimg&quot; src=&quot;https://static.realmofempires.com/images/email/bottomgrad.png&quot; border=&quot;0&quot; style=&quot;width:480px; margin: 0px;display:block;&quot;/&gt;&lt;/td&gt;&lt;/tr&gt;	
        ///			&lt;tr&gt;&lt;td style=&quot;padding: 0px;&quot;&gt;&lt;img class=&quot;mainimg&quot;  src=&quot;https://static.realmofempires.com/images/email/lower.jpg&quot; border=&quot;0&quot; style=&quot;width:480px; m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_verifyrecoveryemail_footer {
            get {
                return ResourceManager.GetString("email_verifyrecoveryemail_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi &lt;strong&gt;{0}&lt;/strong&gt; from &lt;strong&gt;{1}&lt;/strong&gt;,&lt;BR/&gt;&lt;BR/&gt;Please confirm your email address by clicking &lt;a href=&apos;{2}/Verify.aspx?uid={3}&apos;&gt;here&lt;/a &gt;.
        ///
        ///&lt;BR&gt;&lt;BR&gt;&lt;span style=&quot;font-size: 10px;&quot;&gt; If you did not register for a new account or did not request an email change please ignore this email.&lt;/span&gt;
        ///
        ///&lt;BR/&gt;&lt;BR/&gt;Sincerely,&lt;BR/&gt;&lt;strong&gt;The Realm of Empires Team.&lt;/strong&gt;&lt;BR/&gt; &lt;BR/&gt;.
        /// </summary>
        internal static string email_verifyrecoveryemailbody {
            get {
                return ResourceManager.GetString("email_verifyrecoveryemailbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm of Empires recovery email verification..
        /// </summary>
        internal static string email_verifyrecoveryemailsubject {
            get {
                return ResourceManager.GetString("email_verifyrecoveryemailsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a courtesy information email, telling you that you have been blocked by another player. 
        ///    
        ///    This email does not suggest that you did anything wrong, it just tells you that someone blocked you which MAY be a sign that someone found your communications offensive. Repeated blocks will flag you 
        ///    for investigation as we try to ensure that everyone is following the Terms of Use. 
        ///    
        ///    Violations of the TOU may result in a suspension or ban from communication channels, the realm, or RoE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email_youHaveBeenBlocked_body {
            get {
                return ResourceManager.GetString("email_youHaveBeenBlocked_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been blocked by another player.
        /// </summary>
        internal static string email_youHaveBeenBlocked_subject {
            get {
                return ResourceManager.GetString("email_youHaveBeenBlocked_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&apos;https://static.realmofempires.com/images/units/infantry.jpg&apos; align=&apos;left&apos; style=&apos;padding:2px;&apos;/&gt; &lt;B&gt;Hail {0}&lt;/B&gt;! &lt;BR&gt;&lt;BR&gt;&lt;BR&gt;
        ///
        ///A friend whose invitation you accepted when registering, has claimed their reward of you reaching a title of Knight! As a thank you for your dedication, please accept a small gift of 5 servants as well. &lt;BR&gt;&lt;BR&gt;&lt;BR&gt;
        ///
        ///Did you know that you can also claim rewards for recruiting other Knights into the game? &lt;a href=&quot;Invites_AcceptedInvites.aspx&quot;&gt;Please click here for det [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email2_body {
            get {
                return ResourceManager.GetString("email2_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept this gift of 5 servants!.
        /// </summary>
        internal static string email2_subject {
            get {
                return ResourceManager.GetString("email2_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are under attack! : Landing at {0} game time..
        /// </summary>
        internal static string notification_attack {
            get {
                return ResourceManager.GetString("notification_attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner protection runs out in just {0} hours..
        /// </summary>
        internal static string notification_bdpending {
            get {
                return ResourceManager.GetString("notification_bdpending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} invited you to join {2}..
        /// </summary>
        internal static string notification_claninvite {
            get {
                return ResourceManager.GetString("notification_claninvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received and email from {0} on {1}..
        /// </summary>
        internal static string notification_email {
            get {
                return ResourceManager.GetString("notification_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your kingdom in {0} is about to be abandoned!.
        /// </summary>
        internal static string notification_inactive {
            get {
                return ResourceManager.GetString("notification_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string notification_quest {
            get {
                return ResourceManager.GetString("notification_quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string notification_research {
            get {
                return ResourceManager.GetString("notification_research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string notification_takingavillage {
            get {
                return ResourceManager.GetString("notification_takingavillage", resourceCulture);
            }
        }
    }
}
